name: Dataset Update

on:
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC every day
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  update-dataset:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[force update]') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow datasets huggingface_hub boto3 s3fs python-dotenv

      - name: Run dataset update script
        env:
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: python hf_to_R2.py
